# Site settings
title: Alec Rippberger
email: arippberger@gmail.community
description: > # Alec Rippberger's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/alec', 'fa-user']
single_footer: '<p>Alec Rippberger &copy; 2015 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']

# Build settings
markdown: kramdown
